# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Skills' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skills
  pod 'Kingfisher', '~> 4.0'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
end
